FROM public.ecr.aws/lambda/nodejs:20

WORKDIR /var/task

# Copiar package.json e instalar dependencias
COPY package*.json ./
RUN npm install

# Copiar el código de la Lambda y carpeta shared
COPY . .

# Comando de ejecución
CMD ["updateChampion.handler"]
